### ISSUE TITLE
MonoTouch\FSharp.Core.dll fails to resolve BigInteger

### ISSUE THREAD

**Issue by ctaggart** [fsharp/fsharp#363]
I tried out the `MonoTouch\FSharp.Core.dll` in `3.1.2.1` on our iPad app and it doesn't work. I get the error: `error MT2002: Failed to resolve "System.Numerics.BigInteger" reference from "FSharp.Core, Version=2.3.98.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"`.

![image](https://cloud.githubusercontent.com/assets/80104/5591667/caa19b9c-912a-11e4-9e0f-f65d01d19d68.png)

What I find really strange is that the `FSharp.Core.dll` shipped with Xamarin.iOS is bundling these types:
 * System.Collections.IStructuralComparable
 * System.Collections.IStructuralEquatable
 * System.Numerics.BigInteger

```
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\FSharp.Core.dll"
```
![image](https://cloud.githubusercontent.com/assets/80104/5591665/850e8720-912a-11e4-826e-ad53797f8cb2.png)

The one that we shipped in `3.1.2.1` doesn't bundle those types:
```
FSharp.Core.3.1.2.1\lib\MonoTouch\FSharp.Core.dll
```
![image](https://cloud.githubusercontent.com/assets/80104/5591666/a347be6e-912a-11e4-887c-b3346c520977.png)

Why was this done? What is the best to go about resolving this?

/cc @7sharp9

**Comment by 7sharp9** [comment]
The history of the FSharp.Targets file should show when it was changed.  

As far as I was aware big int is not supported.  I can't comment on the other types until I get back to a computer. 

D.

**Comment by ctaggart** [comment]
I checked the previous `FSharp.Core.MonoSigned` and it has those three types.

nuget install fsharp.core.mono.signed -version 3.1.1.27
"C:\tmp\FSharp.Core.Mono.Signed.3.1.1.27\lib\MonoTouch\FSharp.Core.dll"

When working on https://github.com/fsharp/fsharp/issues/359, I made it so the MonoDroid and MonoTouch assemblies were build by AppVeyor. I added this to the `build.bat`:
```
%_msbuildexe% src\fsharp-library-build.proj /p:TargetFramework=monodroid /p:Configuration=Release /p:KeyFile=..\..\..\mono.snk
%_msbuildexe% src\fsharp-library-build.proj /p:TargetFramework=monotouch /p:Configuration=Release /p:KeyFile=..\..\..\mono.snk
```
I thought that would do the trick, but apparently I missed something. Any ideas?

**Comment by ctaggart** [comment]
In `src\FSharpSource.targets`, if I add these two options for `monotouch` and `monodroid`, those three types get included like before.
```
    <DefineConstants>$(DefineConstants);FX_NO_BIGINT</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_STRUCTURAL_EQUALITY</DefineConstants>
```

**Comment by dsyme** [comment]
I don't yet understand the original error report.  I thought these types are available in mscorlib.dll and System.Numerics.dll for montouch and monodroid?  So why is the static linking tool trying to find them in FSharp.Core.dll? Is it because the Xamarin.iOS copy of FSharp.Core is being used during compilation and/or static linking?

If so, I think this may be a case that the right thing in the long term is to update the FSharp.Core.dll being used by Xamarin.iOS.

**Comment by ctaggart** [comment]
I also don't understand why those types are in FSharp.Core.dll. I do know that they are in the one bundled by Xamarin and that they need to be in the dll used from the NuGet package in order to be compatible.

**Comment by dsyme** [comment]
OK.

* It seems ok to update the packages to contain this fix so the latest version is compatible with the current released Xamarin.iOS.

* However I think we should commit the fix to this repo (or at least not to master), because we want the next build of Xamarin.iOS to include a new FSharp.Core that doesn't contain the types.
