### ISSUE TITLE
Partially applied async function hangs when compiled in release mode

### ISSUE THREAD

**Issue by jamesjrg** [fsharp/fsharp#480]
Using .NET 4.5, F# 3.1, F# Core 4.3.1.0, Visual Studio 2013, Windows 8.1

This program hangs when compiled as Release, but not when compiled as Debug, not sure if it is a bug or if I just misunderstand something:

```
module Modulartastic =
    type MrsRecordType = {
        StringProperty : string }

    let partialAsyncFunc _ () = async { return true }

    let testFunc partialAsyncFunc = async {    
        return! partialAsyncFunc() }

    let parameter = {
        MrsRecordType.StringProperty = "hello" }

    let result =
        testFunc (partialAsyncFunc parameter)
        |> Async.RunSynchronously

[<EntryPoint>]
let main argv =
    0
```

**Comment by enricosada** [comment]
Hi @jamesjrg , language/core library issues should be submitted and fixed in the https://github.com/Microsoft/visualfsharp repo, can you create a new issue there?

This repo is for cross platform packaging, see http://fsharp.github.io/2014/06/18/fsharp-contributions.html for a guide

I can repro the bug.

Only an info: i see an empty main

```fsharp
[<EntryPoint>]
let main argv =
    0
```

shouldn't be 

```fsharp

open Modulartastic

[<EntryPoint>]
let main argv =
    let parameter = {
        MrsRecordType.StringProperty = "hello" }

    let result =
        testFunc (partialAsyncFunc parameter)
        |> Async.RunSynchronously

    0
```

instead? You are executing the RunSynchronously code in the initialization of the module, instead of inside the main function (the entry point of the application)

**Comment by jamesjrg** [comment]
Sorry, I've now moved the issue to the other project. If the async function is run in the main method then it no longer hangs, but as I understand things it should also be possible to have it in the module initialization code without hanging the program.

**Comment by enricosada** [comment]
Sure, thx @jamesjrg . i was trying to write a workaround

ref Microsoft/visualfsharp#604
