### ISSUE TITLE
MSBuild and F# 4.0 broken with Mono 4.4.1 on OS X

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#583]
When building Logary with Mono 4.4.1, tests (specifically Heka tests) don't run on OS X because it seems the F# targets move the reference dlls into the app folder; which then the mono runtime tries to use for execution, which cause IL errors since they are missing method bodies.

#### Repro steps

Provide the steps required to reproduce the problem

1. Check out Logary
2. Build logary with `bundle exec rake` – this will work
3. Build again with msbuild; `msbuild src/Logary.sln` – it will copy reference dlls to the wrong location.
3. If you run a `*.Tests.exe` file you'll get a crash, because the reference dlls don't contain implementations.

#### Expected behaviour

Not crashing, not copying the reference dlls.

#### Actual behavior

![DLLs copied to output folders](https://files.gitter.im/mono/mono/veQP/thumb/blob.png) – in fact they are copied.

#### Known workarounds

Downgrade mono + F# targets file to 4.2.3.

#### Related information 

Provide any related information 

* Operating system; OS X
* Branch; ??
* .NET Runtime, CoreCLR or Mono Version; 4.4.1
* Editing Tools (e.g. Visual Studio Version); albacore
* Links to F# RFCs or entries on http://fslang.uservoice.com; no
* Links to performance testing scripts; no
* Indications of severity; Severe, since it makes it next to impossible to use F# on Mac.

**Comment by haf** [comment]
Ping, this is rather urgent.

**Comment by akoeplinger** [comment]
This turns out to be because albacore (before v2.5.14) prefers `msbuild` over `xbuild`. In Mono 4.4 we shipped a preview version of the xplat OSS MSBuild under that name, so it gets used automatically.

However, there seems to be an issue in that this causes the reference assemblies (they contain no actual IL) of some framework libraries like System.Security.dll are copied to the output folder, which makes Mono blow up when it tries to load them.

**Comment by dsyme** [comment]
@akoeplinger Is there a workaround?

**Comment by akoeplinger** [comment]
@dsyme yes, the workaround is making sure xbuild is used instead of msbuild.

The latest version of albacore does that: https://github.com/Albacore/albacore/commit/fadb48f3a7ed3d8c081b370ca7786fa31bded9db

We're also discussing renaming msbuild to msbuild-preview to prevent this for the time being.

/cc @migueldeicaza

**Comment by akoeplinger** [comment]
>We're also discussing renaming msbuild to msbuild-preview to prevent this for the time being.

The decision was to not do this. Users will need to make sure to use xbuild on Mono if they run into issues with the xplat OSS MSBuild (e.g. by using latest albacore).
