### ISSUE TITLE
C# can not find FSharpType.IsRecord in .NET Core

### ISSUE THREAD

**Issue by pocketberserker** [fsharp/fsharp#668]
Some FSharpType and FSharpValue methods are defined by F# Type Extensions.
However, C# can not access F# Type Extensions.
And Some methods are not defined in .NEt Core( https://github.com/fsharp/fsharp/blob/4.1.0.0/src/fsharp/FSharp.Core/reflect.fsi#L266 ).

#### Repro steps

1. `dotnet new classlib -lang C#` and add `<PackageReference Include="FSharp.Core" Version="4.1.0" />`.

2. Call `Microsoft.FSharp.Reflection.FSharpType.IsUnion`

#### Expected behavior

Build succeeded.

#### Actual behavior

```
error CS0117: 'FSharpType' does not contain a definition for 'IsRecord'
```

#### Related information 

sample project: https://github.com/pocketberserker/FSharpNETCoreSandbox/tree/2fdd6fa60cb3989458f96e77a0265064593e9ae7

**Comment by dsyme** [comment]
@pocketberserker Per CONTIRUBITING.md this should be added as an issue to http://github.com/Microsoft/visualfsharp, thanks

It is unfortunate that C# can't call the methods in [``FSharpReflectionExtensions``](https://github.com/fsharp/fsharp/blob/4.1.0.0/src/fsharp/FSharp.Core/reflect.fsi#L363) just because of the compile names containing a ``.``.  This is definitely something we need to fix as it is important for core C# libraries to be able to do this.  As a workaround you could call them via reflection I believe?

**Comment by pocketberserker** [comment]
@dsyme ok. I'll do that.

I try to use reflection and build succeeded. https://github.com/pocketberserker/FSharpNETCoreSandbox/blob/443c35362cbdd167e59ffea03c535fbc251b212e/CsNETCore/Sandbox.cs#L11
Thank you!

**Comment by pocketberserker** [comment]
closing to move to visualfsharp repository
