### ISSUE TITLE
F# 4.1 breaks on Mono 4.6

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#674]
1. Upgrade the nuget to 4.1.
2. Compile
3. Try to run

```
Can't find custom attr constructor image: /Users/rp/recq/src/ReCQ.dll mtoken: 0x0a000001
due to Could not load file or assembly or one of its dependencies. assembly:FSharp.Core, 
Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:<unknown type>
 member:<none>
```

**Comment by matthid** [comment]
might be related to https://github.com/Microsoft/visualfsharp/issues/2566 or https://github.com/fsharp/fsharp/issues/672

**Comment by haf** [comment]
Maybe, but mono 4.6.2 supports .Net 4.5.

**Comment by dsyme** [comment]
@haf Is your FSHarp.Core marked CopyLocal (i.e. Private) so it is part of your deployed application?  

I suspect you are relying on FShrp.Core being in the GAC courtesy of the Mono installation? The Mono package will currently put on FSharp.Core 4.4.0.0 in the GAC.  Eventually that will be updated (or we will have the Mono installation stop putting FSharp.Core in the GAC at all, since that's what's happened on Windows)

**Comment by haf** [comment]
<img width="512" alt="image" src="https://cloud.githubusercontent.com/assets/193115/23822732/11d5af36-0653-11e7-9f5c-d4121081c28e.png">

Well, the fsproj file is done with paket and paket is seemingly copying the dll by default.

**Comment by haf** [comment]
Sorry, I'm out of context for this issue by now. Closing.
