### ISSUE TITLE
FSharp.Core package should not depends on System.ValueTuple nupkg on .NET 4.7

### ISSUE THREAD

**Issue by enricosada** [fsharp/fsharp#741]
`FSharp.Core` v4.1.* already depends on `System.ValueTuple` nupkg (unless target framework is `netstandard1.6` ), because is added as dependency in the fallback group.

Now .NET 4.7 include `System.ValueTuple` so that package should be restricted to no include `net47`

As a note: if FSharp.Core package should depend or not on `System.ValueTuple` for v4.2 is in discussion in https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1034-fsharp-core-package.md

**Comment by matthid** [comment]
Can please someone comment on how the exact rules are for dependency groups are? I think it's kind of important to get them right on FSharp.Core.

There is some documentation [here](https://docs.microsoft.com/en-us/nuget/schema/nuspec).
But it's really really short and from the description I'd actually assume that the reverse is happening to what @enricosada is reporting above: Because if you think about it netstandard16 is compatible with net4.7, correct? therefore I'd assume that the dependencies of the netstandard group are pulled and NOT 'System.ValueType'...

It would be really nice if an expert on NuGet could comment on this as even different versions of NuGet seem to behave differently on this. /cc @cartermp

**Comment by cartermp** [comment]
I'm not sure how  dependency groups work with NuGet.  @ericstj, think you might be able to help out here?

**Comment by ericstj** [comment]
Same as all other assets in NuGet, they select the single best one for the configuration.  There is no layering of dependency groups.  There is no association of the dependency group with any other assets (eg: just because you got a netstandard1.0 lib, you could get a net45 dependency group if that existed and you were targeting net45).  /cc @emgarten

**Comment by emgarten** [comment]
> therefore I'd assume that the dependencies of the netstandard group are pulled and NOT 'System.ValueType

That is what *should* happen when selecting dependencies from the nuspec from what I see. As @ericstj mentioned the single best match is selected, groups are **not** combined. 

@enricosada would you give an example of what you are expecting and what dependencies are showing up if you are seeing different behavior?

**Comment by dsyme** [comment]
Closing as FSharp.Core issues should now be tracked [here](http://github.com/Microsoft/visualfsharp)

**Comment by forki** [comment]
I think we should not close issues without creating the moved issue. This issue is still present in the ecosystem. @matthid can please open a moved issue over there?
