### ISSUE TITLE
FSharp.Core in GAC

### ISSUE THREAD

**Issue by nosami** [fsharp/fsharp#768]
I wanted to start a discussion here to see if there are good reasons for keeping FSharp.Core in the GAC on Mono.

As far as I understand it, FSharp.Core used to be in the GAC on Windows, but now that's no longer the case.

Having this assembly in the GAC makes it more difficult to consume the NuGet version. We needed to remove it from the Xamarin.Android GAC recently for exactly this reason - users were referencing the NuGet version of FSharp.Core but the resulting build was building against the GAC version.

Miguel brought this issue up yesterday [here](https://bugzilla.xamarin.com/show_bug.cgi?id=58549)

**Comment by dsyme** [comment]
> I wanted to start a discussion here to see if there are good reasons for keeping FSharp.Core in the GAC on Mono.

No, probably not, especially if it is causing problems now.  I think we can just take it out and live with the consequences.  All the policy DLLs can also be removed.

Can you submit a PR, or should I?

Thanks

**Comment by dsyme** [comment]
@nosami I took a look and have one technical question (perhaps @migueldeicaza or other could help answer)

**Install FSharp.Core as reference assembly?** 

My feeling is that we should install FSharp.Core into a "Reference Assemblies" location, since that is what the Visual F# Tools do for these assemblies.

Background - Historically we have added several "old" versions of FSharp.Core to the GAC as well
```
/usr/lib/mono/gac/FSharp.Core:
total 40
drwxr-xr-x 2 root root 4096 Aug  4 23:21 3.259.41.0__b03f5f7f11d50a3a
drwxr-xr-x 2 root root 4096 Aug  4 23:21 3.47.41.0__b03f5f7f11d50a3a
drwxr-xr-x 2 root root 4096 Aug  4 23:21 3.7.41.0__b03f5f7f11d50a3a
drwxr-xr-x 2 root root 4096 Aug  4 23:21 3.78.41.0__b03f5f7f11d50a3a
drwxr-xr-x 2 root root 4096 Aug  4 23:21 3.98.41.0__b03f5f7f11d50a3a
drwxr-xr-x 2 root root 4096 Aug  4 23:21 3.99.41.0__b03f5f7f11d50a3a
drwxr-xr-x 2 root root 4096 Aug  4 23:21 4.3.0.0__b03f5f7f11d50a3a
drwxr-xr-x 2 root root 4096 Aug  4 23:21 4.3.1.0__b03f5f7f11d50a3a
drwxr-xr-x 2 root root 4096 Aug  4 23:21 4.4.0.0__b03f5f7f11d50a3a
drwxr-xr-x 2 root root 4096 Aug  4 23:21 4.4.1.0__b03f5f7f11d50a3a
```

I believe an F# project reference of ``<Name>FSharp.Core</Name>`` with some specific version-based reference would find these - I could look up the details of examples of project files.  The question is whether we install these at some appropriate place on Linux so that they can be found as reference assemblies. This would be in the same way that they are installed in Reference Assemblies on windows.  If we don't I believe we will cause hard failures in existing F# project compilations, requiring them to move to using the FSharp.Core nuget package.

My feeling is that we should install FSharp.Core into a "Reference Assemblies" location, since that is what the Visual F# Tools do for these assemblies, and we should seek parity with Windows installations so like-for-like project files continue to compile.

Other notes (things which I don't think are a problem but which we should keep an eye on)

* There is a GAC DLL ``FSharp.Compiler.Server.Shared.dll`` which is needed by ``fsi.exe``.  I believe this will be found ok as it is in the same directory as ``fsi.exe``

* There is a GAC DLL ``FSharp.Compiler.Interactive.Settings.dll`` which is needed at runtime by ``fsi.exe``, and also is injected as an implicit  ``#r`` reference for the F# scripting model.  I believe this will be found ok by ``fsi.exe`` for both runtime and referencing as it is in the same directory as ``fsi.exe``

**Comment by dsyme** [comment]
@nosami @migueldeicaza See here: https://github.com/fsharp/fsharp/pull/771

**Comment by nosami** [comment]
> Install FSharp.Core as reference assembly?

This seems like a great idea. I haven't seen anything equivalent to "Reference Assemblies" in Mono though. Linux has a separate reference-assemblies package, but as far as I understand, this is just used for PCL facade binaries. @akoeplinger should know more about this.

**Comment by dsyme** [comment]
>  I haven't seen anything equivalent to "Reference Assemblies" in Mono though. Linux has a separate reference-assemblies package, but as far as I understand, this is just used for PCL facade binaries. @akoeplinger should know more about this.

Yeah, that's what I thought.  @akoeplinger - advice welcome, thanks!

**Comment by akoeplinger** [comment]
Hmm, we don't have an equivalent to the "Reference Assemblies" folder, we do have `<prefix>/lib/mono/xbuild-frameworks` though which is basically `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework`.

However, we do seem to already have some sort of reference assemblies folder in `/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/api`:

```
├── api
│   ├── .NETCore
│   │   ├── 3.259.41.0
│   │   │   ├── FSharp.Core.dll
│   │   │   ├── FSharp.Core.optdata
│   │   │   ├── FSharp.Core.sigdata
│   │   │   └── FSharp.Core.xml
│   │   ├── 3.7.41.0
│   │   │   ├── FSharp.Core.dll
│   │   │   ├── FSharp.Core.optdata
│   │   │   ├── FSharp.Core.sigdata
│   │   │   └── FSharp.Core.xml
│   │   └── 3.78.41.0
│   │       ├── FSharp.Core.dll
│   │       ├── FSharp.Core.optdata
│   │       ├── FSharp.Core.sigdata
│   │       └── FSharp.Core.xml
│   ├── .NETFramework
│   │   └── v4.0
│   │       ├── 4.3.0.0
│   │       │   ├── FSharp.Core.dll
│   │       │   ├── FSharp.Core.optdata
│   │       │   ├── FSharp.Core.sigdata
│   │       │   └── FSharp.Core.xml
│   │       ├── 4.3.1.0
│   │       │   ├── FSharp.Core.dll
│   │       │   ├── FSharp.Core.optdata
│   │       │   ├── FSharp.Core.sigdata
│   │       │   └── FSharp.Core.xml
│   │       ├── 4.4.0.0
│   │       │   ├── FSharp.Core.dll
│   │       │   ├── FSharp.Core.optdata
│   │       │   ├── FSharp.Core.sigdata
│   │       │   └── FSharp.Core.xml
│   │       └── 4.4.1.0
│   │           ├── FSharp.Core.dll
│   │           ├── FSharp.Core.optdata
│   │           ├── FSharp.Core.sigdata
│   │           └── FSharp.Core.xml
│   └── .NETPortable
│       └── 3.47.41.0
│           ├── FSharp.Core.dll
│           ├── FSharp.Core.optdata
│           ├── FSharp.Core.sigdata
│           └── FSharp.Core.xml
```

This is the same folder structure that I see in `C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\` on Windows. Perhaps that is enough?

**Comment by nosami** [comment]
I'll give this some testing.

I think we just need references of this form to work without any assemblies in the GAC

```
    <Reference Include="FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
```

**Comment by nosami** [comment]
Currently, `<Reference Include="FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />` resolves on OSX to 

`
 /Library/Frameworks/Mono.framework/Versions/5.4.0/lib/mono/gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/FSharp.Core.dll
` as this assembly is stored in the GAC.

If I try the same thing on Windows, it resolves to `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PublicAssemblies\FSharp.Core.dll`. even though this assembly is not stored in the GAC

Digging a little to see how this works, I see the following in the diagnostic output.
```
        C:\Users\jason\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\bin\Debug\FSharp.C
ore.dll
                CopyLocal=true
                FusionName=FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                ImageRuntime=v4.0.30319
                OriginalItemSpec=FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                ReferenceSourceTarget=ResolveAssemblyReference
                ResolvedFrom={AssemblyFoldersFromConfig:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
MSBuild\15.0\bin\AssemblyFolders.config,v4.5.2}
                Version=4.4.1.0
```

```
 Primary reference "FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". (TaskId:11)
      Resolved file path is "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PublicAssemblie
  s\FSharp.Core.dll". (TaskId:11)
      Reference found at search path location "{AssemblyFoldersFromConfig:C:\Program Files (x86)\Microsoft Visual Studi
  o\2017\Enterprise\MSBuild\15.0\bin\AssemblyFolders.config,v4.5.2}". (TaskId:11)
          For SearchPath "{TargetFrameworkDirectory}". (TaskId:11)
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\FSharp.Core.
  winmd", but it didn't exist. (TaskId:11)
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\FSharp.Core.
  dll", but it didn't exist. (TaskId:11)
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\FSharp.Core.
  exe", but it didn't exist. (TaskId:11)
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\FSha
  rp.Core.winmd", but it didn't exist. (TaskId:11)
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\FSha
  rp.Core.dll", but it didn't exist. (TaskId:11)
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\FSha
  rp.Core.exe", but it didn't exist. (TaskId:11)
          For SearchPath "{AssemblyFoldersFromConfig:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSB
  uild\15.0\bin\AssemblyFolders.config,v4.5.2}". (TaskId:11)
          Considered "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\S
  qlDb\FSharp.Core.winmd", but it didn't exist. (TaskId:11)
          Considered "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\S
  qlDb\FSharp.Core.dll", but it didn't exist. (TaskId:11)
          Considered "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\S
  qlDb\FSharp.Core.exe", but it didn't exist. (TaskId:11)
          Considered "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PublicAssemblies\FShar
  p.Core.winmd", but it didn't exist. (TaskId:11)
```

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin>AssemblyFolders.config contains the following
```xml
    <AssemblyFolder>
      <Name>Public Assemblies</Name>
      <FrameworkVersion>v4.5.25000</FrameworkVersion>
      <Path>%VSINSTALLDIR%\Common7\IDE\PublicAssemblies\</Path>
    </AssemblyFolder>
```
which is used to locate FSharp.Core.dll (presumably installed with VS)

Visual Studio on Windows templates reference FSharp.Core like this :-

```
    <Reference Include="FSharp.Core">
      <Name>FSharp.Core</Name>
      <AssemblyName>FSharp.Core.dll</AssemblyName>        
      <HintPath>$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\$(TargetFSharpCoreVersion)\FSharp.Core.dll</HintPath>
    </Reference>
```

**Comment by nosami** [comment]
It seems to me that we could do the same thing for Mono by specifying

$MONOPREFIX/lib/mono/fsharp/api as a valid search path inside AssemblyFolders.config

**Comment by migueldeicaza** [comment]
Question: once FSharp.Core is removed from the GAC, is fsharpc supposed to produce executables with a side-by-side fsharp.core to use?

**Comment by dsyme** [comment]
> Question: once FSharp.Core is removed from the GAC, is fsharpc supposed to produce executables with a side-by-side fsharp.core to use?

On Windows (where FSharp.Core is not in the GAC) a command line such as ``fsharpc test.fs`` copies the implicitly referenced FSharp.Core.dll to the output directory, so you can immediately run ``test.exe`` (it will also copy  This is really a hack to make "intro command line samples" from various F# books work as documented. However it doesn't work in general since no other dependencies are copied, though it gets you a long way since F# code over the vanilla .NET Framework references is a really powerful programming tool.

When used from Visual Studio, MSBuild, XBuild or Xamarin Studio a copy-local of FSharp.Core done is well but this is only to the intermediate output path e.g. ``obj\Debug`` and this is not copied to OutputPath except if MSBuild decides to copy.  This rather needless copying is basically harmless and could be avoided - indeed the new .NET SDK build support doesn't do it any more.

On Linux/OSX/Mono we originally disabled the copying since FSharp.Core was in the GAC and it wasn't really neeeded.  Recently we started doing it for parity, e.g. [this](https://github.com/fsharp/fsharp/blob/master/src/fsharp/CompileOps.fs#L2328)

On Windows we didn't observe any really systematic problems by taking FSharp.Core out of the GAC - fewer problems than I expected. The use of copy-local of FSharp.Core probably handled a bunch of real-world cases where people were using ``fsc.exe`` directly from the command-line, and people worked through the rest.  No one reported negative results from the copy-local, though it may give rise to the impression that using ``fsc.exe`` directly from the command line is "odd"

**Comment by dsyme** [comment]
FSharp.Core is now removed from the GAC on Linux
