### ISSUE TITLE
build fails on KaOS OS

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fsharp#784]
I run into a couple of build failures on my Linux based device. 

First of, the compilation with Mono fails since it conflicts with a well known issue, related to OpenSSL that is obviously open since [one year](https://github.com/dotnet/corefx/issues/9855). 

[This page](https://www.nuget.org/packages/FSharp.Compiler.Tools/) lacks any information that I have to create a project, before I can successfully use the package manager. 

It is common practice, that package managers work out of the box and without relevance to the projects.

I solved it with the help of a community member, just in order to detect, that an essential feature is [missing](https://github.com/dotnet/cli/issues/3913). 

I suggest an [AppImage](https://appimage.org/), which is one way to get software bundled on all Linux distros. There are similar alternatives, like Habitat Flatpak and so on.

KaOS is the used OS here.

**Comment by dsyme** [comment]
@ShalokShalom I'm not sure of the specific request here - is it related to building F# support for .NET Core?  Or with Mono?   Or using the tools from the nuget package?

thanks

**Comment by ShalokShalom** [comment]
All that. 

My goal is to get a working fsharp compiler with a REPL. 

I prefer now to build it with Mono, which includes that https://github.com/dotnet/corefx/issues/9855 is solved.

Thanks

**Comment by enricosada** [comment]
@ShalokShalom need some info:

- what are the steps you are doing
- the error log of build failure

if is a build failure of this repo makefile, please post it there.

This repo (like F#) has some dependencies, because require a .net runtime and sdk:

- or mono
- or .net core

The runtime has the deps on openssl, not F# itself

The supported platform/os of mono are http://www.mono-project.com/docs/about-mono/supported-platforms/

The supported platform/os of .net core are https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md

Atm i dont see the `KaOS` as supported OS in either

- If your os is not supported on mono, you should open an issue in [mono bugzilla](https://bugzilla.xamarin.com/)
- if your os is not supported on .net core, you should open an issue in [dotnet/core github](https://github.com/dotnet/core/issues)

> This page lacks any information that I have to create a project, before I can successfully use the package manager.

See https://github.com/fsharp/fsharp#building-on-linux-and-other-unix-systems about builing on linux

> First of, the compilation with Mono fails since it conflicts with a well known issue, related to OpenSSL that is obviously open since one year.

Open an issue in mono bugzilla about it

> I solved it with the help of a community member, just in order to detect, that an essential feature is missing (repl on .net core).

the repl on .net core (fsi) is not supported atm, the issue is tracked in https://github.com/Microsoft/visualfsharp/issues/2407
Only on mono is works atm

> I suggest an AppImage for all Linux distributions and the update of OpenSSL.

Please open an issue in the mono or .net core repo about it

**Comment by ShalokShalom** [comment]
Hi there and thanks a lot ^-^

> what are the steps you are doing

This is the build script: 

```
pkgname=fsharp
pkgver=4.1.18
pkgrel=1
pkgdesc="The Open Edition of the F# compiler, core library and tools"
arch=('x86_64')
url="http://fsharp.org/"
license=('Apache')
depends=('mono')
makedepends=(git)
_commit=3245fd24efcc7a54d4314a2897257f68cd194244
source=("git+https://github.com/fsharp/fsharp/#commit=$_commit")
sha256sums=('SKIP')

pkgver() {
  cd $pkgname
  git describe --tags | sed 's/-/+/g'
}

build() {
  cd "$srcdir/$pkgname"
  ./autogen.sh --prefix=/usr
  make
}

package() {
  cd "$srcdir/$pkgname"
  make DESTDIR="$pkgdir" install
}
```

Its to create a package, this why those sections on the bottom. 

> the error log of build failure

https://gist.github.com/ShalokShalom/4e8da846fe80ff54fd0129332e2bca75

Mono is supported here. Linux based operating systems use different packages, which means different versions of the specific software. KaOS can run all the code, which is build for x86_64 Linux.

**Comment by knocte** [comment]
I see in the log this error:
```
WARNING: Unable to find version '1.4.2' of package 'System.Reflection.Metadata'.
  /home/matthias/.nuget/packages/: Package 'System.Reflection.Metadata.1.4.2' is not found on source '/home/matthias/.nuget/packages/'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request
  Error: TrustFailure (One or more errors occurred.)
  One or more errors occurred.
  A call to SSPI failed, see inner exception.
  Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
at /home/matthias/Projekte/KaOS/makepkg/mono/src/mono-5.4.0.167/external/boringssl/ssl/handshake_client.c:1132
```
This seems to indicate you either have internet connection problems, or SSL problems. If it's the later, can you tell us what version of mono are you using?

**Comment by ShalokShalom** [comment]
This happens with both, 4.8 and 5.4

I use my Internet in a high variety of other cases, it works fine.
How can I detect SSL issues?

**Comment by ShalokShalom** [comment]
How can I build with OpenSSL 1.1, when there is an open report about it, which explains, that it is unsupported currently?

**Comment by ShalokShalom** [comment]
This reminds me so much on this: https://www.reddit.com/r/Surface/comments/6u1evy/the_lack_of_net_native_support_for_f_caused/

Several thousand developers get blocked right away, nobody cares and later on, everybody is crying about "to less adoption" Seriously?

**Comment by knocte** [comment]
@ShalokShalom not to be dismissive here, but given that you mention(ed) KaOS in your github issue, it seems we're talking about a very specific usecase here (and not something would affect "thousands of developers"), given that I'm a Linux user/developer for more than a decade and it's the first time I hear about KaOS (I assume it's a Linux distro?).

AFAIU, more mainstream distros don't have SSL problems with Mono because they have implemented the right packaging-hooks to get all the certificate-problems solved. Maybe KaOS is missing all these packaging dance. In which case this would be a downstream bug, and not an upstream one. Look at how Debian packages are doing it maybe? Extract them from here http://www.mono-project.com/download/#download-lin

**Comment by ShalokShalom** [comment]
This effects everybody, who use a current version of OpenSSL.

**Comment by ShalokShalom** [comment]
Debian use an old OpenSSL and Arch provides an such one as an extra package as a workaround, just for FSharp.

The thing is, that I am used to projects, were fundamental software gets implemented really quickly and I assumed that from a huge company like Microsoft, the same thing is obviously.

**Comment by knocte** [comment]
> Debian uses an old OpenSSL and Arch provides such one as an extra package just for FSharp.

Let's try to pinpoint the exact issue here: if you're saying that F# is not compatible with a new version of OpenSSL but only with an old version, please state these 2 versions explicitly, and renaming the issue to that.

The name of the issue shouldn't be a solution proposed.

**Comment by enricosada** [comment]
> The name of the issue shouldn't be a solution proposed

@ShalokShalom i had changed already the title, please dont change it. if you want to add feedback, post a comment.

Changing title (again) from `No AppImage available` to `build fails on KaOS OS`

If you want to discuss about `AppImage`, please open another issue. Mixing discussions in the same issue make a lot harder to fix it and make discussion confusing.

**Comment by ShalokShalom** [comment]
Well, i renamed this issue since it will reappear on any distro that uses a current version of OpenSSL. 

> Let's try to pinpoint the exact issue here: if you're saying that F# is not compatible with a new version of OpenSSL but only with an old version, please state these 2 versions explicitly, and renam the issue to that.

Well, I already linked that in my initial post: fsharp is incompatible with OpenSSL 1.1
