### ISSUE TITLE
Translations of the error messages

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fsharp#786]
I am ready to translate error messages. Is this supported?

**Comment by dsyme** [comment]
@ShalokShalom Only the Microsoft/visualfsharp (.NET Core SDK and Visual F# Tools) release of F# is localized at the moment.

Previously the localization has been closed source but I believe @brettfo is in the process of making all localization open source

**Comment by dsyme** [comment]
cc @brettfo  - Brett, will error message localiation be open for user contributions in the "visualfsharp" repo?

**Comment by brettfo** [comment]
Once I'm done re-working our build, then yes we will be able to take user contributions for translations.  As for when that'll be ready, I can't say yet other than 'it's coming'.

**Comment by ShalokShalom** [comment]
How can I track that one? ^-^

**Comment by brettfo** [comment]
Thanks for the reminder on this.

Our build is in a state now where we can **theoretically** take contributions to translations.  All changes would be made in `*.xlf` files.

Now what does "theoretically" mean?  In short, I don't know.  In our old model of localization, the localization vendors simply overwrite all strings; they are the source of truth and that's the end.  Obviously this won't work going forward and the process should look something like this:

1. User changes a non-English string and submits a PR.
2. Somebody on the Microsoft F# team (probably me) will back-channel the LOC team notifying them of the changed string.
3. Once they give me the go-ahead, the PR will be merged.

Since this hasn't happened yet we don't really have a good process in place, and frankly we'll probably have a poor experience doing this the first couple of times until we figure out what exactly needs to happen and in what order.

Ideally the tools the LOC team uses would be able to merge their own changes with the changes on GitHub, but from what I understand that's not currently possible, hence the need for one of us to back-channel them.

**Comment by ShalokShalom** [comment]
So, how to succeed?

**Comment by ShalokShalom** [comment]
Hi 

Is there any progress? :)

I might like to solve this for 4.2 :slight:smile

**Comment by brettfo** [comment]
We don't yet have a full process in place to handle community-supplied translations, but if you were to submit a PR with the appropriate changes to `Microsoft/visualfsharp:master` I could use that as leverage to try and force some meetings to figure it all out.

**Comment by ShalokShalom** [comment]
Simply translate the current strings?
Which steps are important to set that up to something like [Zanata?](http://zanata.org/)

**Comment by ShalokShalom** [comment]
Simply translate the current strings?
Which steps are important to set that up to something like [Zanata?](http://zanata.org/)

**Comment by brettfo** [comment]
Our translation vendors have their own tools that they use to manage translations and we're working to get them to a point where they can ingest string changes in the wild, which means yes, in theory, you can

> Simply translate the current strings

by directly editing the appropriate `*.xlf` files and submitting a PR which I'll then use to start forcing the translation vendors to handle external (to them) changes.

**Comment by dsyme** [comment]
Note that the Mono packaging of F# doesn't ship localized strings. I think it could but we haven't included it yet.

**Comment by dsyme** [comment]
Translations of messages are handled in Microsoft/visualfsharp, and are out of scope for this repo
