### ISSUE TITLE
Multiple Constructors require different syntax

### ISSUE THREAD

**Issue by ChrSteinert** [fsharp/fsharp#827]
When adding constructors to to an F# class the required syntax changes, e.g. is different for the last constructor (for single parameter `.ctor`s).

#### Repro steps

While the following code is valid…
```F#
type A (a : int option, b : string option) =
    new a = A (a, None)
    member __.X = ""
```

… adding another `.ctor` with one parameter in a similar fashion does not validate anymore:

```F#
type A (a : int option, b : string option) =
    new a = A (a, None)
    new b = A (None, b)
    member __.X = ""
```

The error on the `=` on the third line is: `error FS0010: Unexpected symbol '=' in expression`

#### Known workarounds

Parameters of the not-last `.ctor` must be wrapped in braces. For a yet bigger example this gives:

```F#
type A (a : int option, b : string option, c : float option) =
    new (a) = A (a, None, None)
    new (b) = A (None, b, None)
    new c = A (None, None, c)
    member __.X = ""
```

(Also omitting the first brace (in `new (a)`) does break the thing.)

#### Related information 

Observed on Win 10 in VS and Ionide with latest releases installed.

Severity is most probably low.

**Comment by dsyme** [comment]
@ChrSteinert This is a parser thing where it is thinking `new c` is an expression, e.g. `new Object()`

In the first line it is not seen as ambiguous because there is no possibility of an expression at that point in the syntax (it's one of the only points where that's not possible).

I suppose we should track this as something to give a warning since I can see how you could hit this.Te warning would ask the user to write `new (arg1, ... argN)` in constructor definitions, always using parentheses.

Per CONTRIBUTING.md could you reopen this in http://github.com/Microsoft/visualfsharp please? thanks
