### ISSUE TITLE
StackOverflow hashing a large list

### ISSUE THREAD

**Issue by anticrisis** [fsharp/fsharp#882]
Performing `hash` on a large `List` causes a stack overflow.

#### Repro steps

Provide the steps required to reproduce the problem

1. Evaluate this in FSI or in compiled code:

```fsharp
Array.create 100000 0 |> Array.toList |> hash;;
```

#### Expected behavior

A numeric hash value is returned.

#### Actual behavior

`StackOverflowException`

#### Known workarounds

Unknown.

#### Related information 

Provide any related information 

* Windows
* Visual Studio Community 2017

**Comment by voronoipotato** [comment]
https://github.com/Microsoft/visualfsharp/issues/1838

In the slack chat someone mentioned that this was a known issue.

**Comment by jdh30** [comment]
Yes. You have always been able to crash F# with:

    hash[1..1000000]

IIRC the underlying problem is that the .NET approach to GetHashCode results in arbitrarily-long sequences of non-tail calls that will always stack overflow.

I can envisage various different solutions but none are particularly great:

* The built-in collections shouldn't use GetHashCode recursively and should simply enumerate themselves instead. This is a no-brainer, would be faster and fixes this bug but you'd still get stack overflows when applying hash to any deep values of user-defined types like trees.
* All F# types including both built-in collections and user-defined types (tuples, records, unions) could use continuation passing style to compute their own hashes. This would be reasonably fast but not reliable because tail calls are no longer reliable on any of F#'s target VMs.
* Same thing but with trampolines instead of tail calls. This would be reliable on all targets but ~10x slower.
* Invert control and have a single function that can compute the hash of any value of any F# type. This can use goto instead of tail calls so it should be reliable on any VM but making it efficient might require the use of reflection to generate code for new types as they are encountered.

Objectively, I'd say this is one of the problems best solved at the VM level rather than the language front-end level.

**Comment by rojepp** [comment]
@jdh30 I think the first suggestion is good enough. If you blow the stack with custom recursive types, chances are you'll know what to do.

**Comment by dsyme** [comment]
Closing out issues in this repo, if necessary please reopen at https://github.com/dotnet/fsharp, which is now the unified repository for F# work
