### ISSUE TITLE
Missing code for version 4.5.4 and 4.6.0+

### ISSUE THREAD

**Issue by iNecas** [fsharp/fsharp#895]
When trying to build fsharp from source, I've noticed that in nuget, there are versions 4.5.4, as well as numerous 4.6.z releases, that I was not able to find sources for in here.

Is there anything I'm missing here? Any plans publishing those as well?

Motivation: with open-source projects, I prefer the ability to jump into definitions as deep as I can: this means being able to jump to code from the fsharp core as well. I can't do that without the sources being published somewhere.

**Comment by dsyme** [comment]
@iNecas The FSHarp.Core nuget are co-published by Microsoft and the F# Software Foundation from the https://github.com/Microsoft/visualfsharp repo.  Build-from-source is possible from that repo.

Code is integrated across from that repo to this repo regularly, in order to build the FSharp.COmpiler.Tools package and the various linux Mono packages.  We haven't yet integrated across the code for FSharp.Core 4.6.x

**Comment by iNecas** [comment]
Thanks @dsyme for info. That's explains a lot (and reminds me I should actually read at least the README and not do assumptions). I will look at the upstream repo then.

Anyway, probably makes sense to keep this issue opened until this repo is rebased against 4.6

**Comment by dsyme** [comment]
Closing as https://github.com/dotnet/fsharp is now the unified repository for F# work.
